server:
  port: 8761

eureka:
  instance:
    # 设置eureka的主机地址
    hostname: localhost
  client:
    #表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设置为false
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设置为false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    # 服务模块名称
    name: eureka